server:
  port: 8008

app:
  crypto:
    request:
      url: "www.coingecko.com"
      api: "https://api.coingecko.com/api/v3"
      path-template: "%s/simple/price?ids=%s&vs_currencies=usd"
      header: "x_cg_demo_api_key"
      token: "xCVqoMDWXQpoSpqNTCshp5Ua"
    response:
      json-path-template: "$.%s.usd"
  course:
    api: "https://www.cbr-xml-daily.ru/latest.js"
  stub:
    course:
      coin-usd: 10000
      usd-rub: 100

logging:
  level:
    root: INFO
    com.javaacademy.cryptowallet: DEBUG
